feat: CSV Flatfile Pipeline Testing
mbta/lamp pull request #154
Opened 2023-07-19 10:07 UTC by rymarczy

This PR provides a new testing method `test_whole_table`. This method takes a CSV representation of Vehicle Position records, converts it to a Parquet file on the fly and runs it through `process_gtfs_rt_files` to populate GTFS-RT RDS tables. 

After Processing, a query selects records from the RDS and compares them against a CSV results file to confirm that there have been no fundamental changes to the Performance Manager processing pipelines.

The input CSV file consists of mostly whole route trips, 3 in each direction for each MBTA Rail line. 

This PR required the updating of GTFS and GTFS-RT test files in the `SPRINGBOARD` `test_files` folder of the repository to match that date of records from the flat file (May 8th 2023). In an effort to reduce the repository size, all non rail data has also been stripped from the `SPRINGBOARD` parquet files of `RT_TRIP_UPDATES` and `RT_VEHICLE_POSITIONS`. 

This Branch was developed with a commit from prior to the inclusion of the PR that removed hash columns from the application. This was done to provide a check against the validity of the changes introduced by that PR. 

Asana Task: https://app.asana.com/0/1204931901750655/1205084207879142

2023-07-19 21:05 UTC, mzappitello requested changes
two small change requests, but it looks good to me.

2023-07-19 21:05 UTC, mzappitello commented on python_src/tests/performance_manager/test_performance_manager.py
> +    print(compare_result, flush=True)
only print this if the assert fails?

2023-07-20 10:45 UTC, rymarczy commented on python_src/tests/performance_manager/test_performance_manager.py
> +    os.makedirs(os.path.join(springboard_dir, parquet_folder), exist_ok=True)
Incorporated with pytest `temp_path` fixture.

2023-07-20 10:45 UTC, rymarczy commented on python_src/tests/performance_manager/test_performance_manager.py
> +    print(compare_result, flush=True)
Incorporated.

2023-07-24 16:12 UTC, mzappitello approved these changes
LGTM 🍰

2023-07-25 10:23 UTC, merged