Schedule flat file write 2
mbta/lamp pull request #159
Opened 2023-08-08 03:01 UTC by mzappitello

Create method to write a flat file from the database for a given service date. It joins the Vehicle Events, Vehicle Positions, and Static Stops tables into a format third parties can use to read performance data.

Add flat file writing to performance manager event loop after new data is generated from gtfs realtime files. Write flat files for service dates from newly processed data.

Asana Task: https://app.asana.com/0/1204931901750655/1204907226653447/f
Asana Task: https://app.asana.com/0/1204931901750655/1204907226653449/f

2023-08-08 14:05 UTC, mzappitello commented
This Replaces https://github.com/mbta/lamp/pull/157

2023-08-10 12:11 UTC, rymarczy requested changes
Looks pretty good, a few comments regarding the README documentation and a more general question regarding timestamps vs service_date for the writing of files in the event loop.

2023-08-10 12:11 UTC, rymarczy commented on python_src/src/lamp_py/performance_manager/flat_file.py
> +
I think there is a chance that the service_date pulled from this function won't match the service_date's processed during the event loop. But I'm not totally sure on the edge cases that could cause issues here. 

Might be worth talking through the different variations of possible service_dates's returned compared to service_date's processed based on timezone and time of day variations.

2023-08-15 19:00 UTC, rymarczy approved these changes
LGTM

2023-08-15 19:39 UTC, merged